docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'laminas-cache-storage-adapter-redis'
site_description: ''
repo_url: 'https://github.com/laminas/laminas-cache-storage-adapter-redis'
